// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJYUR1ImiKW3SqnZwrzbyvCoqL6RU0iI',
    appId: '1:360963416965:web:45bb2ba5afbb437ab45aec',
    messagingSenderId: '360963416965',
    projectId: 'reddit-clone-fc5da',
    authDomain: 'reddit-clone-fc5da.firebaseapp.com',
    storageBucket: 'reddit-clone-fc5da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMsB650xNLapxhbge7gu8WPqN0XbSiMBk',
    appId: '1:360963416965:android:df8cec2462e4342cb45aec',
    messagingSenderId: '360963416965',
    projectId: 'reddit-clone-fc5da',
    storageBucket: 'reddit-clone-fc5da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmzRO_bIaNSC5ktHLMTldGmfF9P8j1rdc',
    appId: '1:360963416965:ios:9d002ae6eedefe83b45aec',
    messagingSenderId: '360963416965',
    projectId: 'reddit-clone-fc5da',
    storageBucket: 'reddit-clone-fc5da.appspot.com',
    iosClientId: '360963416965-f9uk27gfkohs93jbkigsi92uis4glahf.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
